fix(graphql): install @parcel/watcher
Fixes the following issue:

    server-1  | (WATCH)   Failed to import @parcel/watcher due to the following error (to use watch mode, install https://www.npmjs.com/package/@parcel/watcher):
    server-1  | (WATCH) Error: Cannot find module '@parcel/watcher'
    server-1  | (WATCH) Require stack:
    server-1  | (WATCH) - /work/node_modules/@graphql-codegen/cli/cjs/utils/watcher.js
    server-1  | (WATCH) - /work/node_modules/@graphql-codegen/cli/cjs/generate-and-save.js
    server-1  | (WATCH) - /work/node_modules/@graphql-codegen/cli/cjs/cli.js
    server-1  | (WATCH) - /work/node_modules/@graphql-codegen/cli/cjs/bin.js